"$schema" = "./node_modules/wrangler/config-schema.json"
name = "lc-admin"
compatibility_date = "2026-04-22"
pages_build_output_dir = "."

[vars]
LIVECHAT_API_VERSION = "v3.6"

[[d1_databases]]
binding = "DB"
database_name = "live_chat_admin"
database_id = "968349fc-7baf-41b1-80f8-be77f0a2b70d"
